- sahara.c
We should return in case we haven't reached the end of the Sahara
init, which is when we set done to true. If done is not set to true
before returning from sahara_run() , it means something went wrong.
Signed-off-by: Nicolas Dechesne <nicolas.dechesne@linaro.org>
> sahara_run: properly propagate error

- util.c
dc61f8f79e924 broke ufs provisioning by requiring base 10 for unsigned
attributes (provisioning xml have some values in hexadecimal). strtoul()
would return 0 for some values and provisioning would fail strangely.
This should resolve https://github.com/andersson/qdl/issues/3
> util: allow hexadecimal values for attr_as_unsigned (fix ufs provisioning)

- sahara.c
Rather than failing with the cryptic message, return early if prog.mbn
can not be found.
Signed-off-by: Dmitry Baryshkov <dmitry.baryshkov@linaro.org>
> qdl: bail out with the sensible error if prog.mbn can not be opened

- firehose.c
The byte offset value for lseek can easily exceed 4GB, cast as off_t to
avoid overflow when converting sectors to bytes for lseek.
(and use lseek64/off64_t so this fixes 32-bit builds of qdl too)
> firehose: fix >4GB lseek file offsets

- README
Without libudev installed you'll get the following build error:
qdl.c:43:10: fatal error: libudev.h: No such file or directory
43 | #include <libudev.h>
|          ^~~~~~~~~~~
compilation terminated.
make: *** [<builtin>: qdl.o] Error 1
Mention the ubuntu package that brings it in as well similar to how
libxml2 is mentioned.
Signed-off-by: Andrew Halaney <ajhalaney@gmail.com>
> readme: Mention libudev requirement

- program.c
When xml has no last_sector, qdl will read xml failed. Add check
to see if last_sector exists
> qdl: Add a fix for read xml error

- patch.c
- program.c
- util.c
this fails to compile using gcc-14 without including stdlib.h in the following files.
> Fix gcc-14 compile errors

- Makefile
- README
- qdl.c
- qdl.h
- ramdump.c
- usb.c
Transitioning to libusb avoids open-coded USB descriptor parsing and removes the strong dependency
on the Linux-specific ioctl-based interface.
This should allow QDL to run on other OSs, it cleans up the code a bit, and it allow us to more conveniently
implement reading of the string descriptors, for a serial number comparison, in the support for selecting a
specific board when more than one is available.
> Transition to libusb and support targeting device by serial number

- program.c
Previously the message would be printed that the tag gets ignored but in reality the 'errors' variable will still be initialized as -EINVAL so the if below would return an error.
[PROGRAM] unrecognized tag "zeroout", ignoring
qdl: program_load rawprogram0.xml failed
Fix this.
> program: fail correctly on unrecognized tags

- Makefile
Append allows an external build system to pass custom cflags/ldflags to the local build system (make).
Useful with Yocto / OE as additional options can be given besides what is set with a force set in the Makefile.
> Makefile: prefer append on CFLAGS / LDFLAGS

- usb.c
libusb commit f0cce43f882d ("core: Fix definition and use of enum libusb_transfer_type") split the types of split transfer type and endpoint transfer, introducing LIBUSB_ENDPOINT_TRANSFER_TYPE_BULK.
The result is that when building with older libusb, such the one available on Ubuntu 20.04 the build fails with the following error:
usb.c:84:16: error: ‘LIBUSB_ENDPOINT_TRANSFER_TYPE_BULK’ undeclared (first use in this function); did you mean ‘LIBUSB_TRANSFER_TYPE_BULK’?
Introduce an alias using the preprocessor to make available the new define when building against the older version of libusb headers.
> usb: Allow building with older libusb

- .github/workflows/build.yml
The transition to libusb was tested on a few different Linux distros, but apparently not Ubuntu 20.04, which contains a slightly older version of the libusb includes.
Add Ubuntu 20.04 as a CI target to catch more such issues, and for good measure also add 24.04.
> ci/build: Build across different Ubuntu variants

- usb.c
In the event that the kernel have some other driver attached to the device the attempt claim of the interface will fail.
Lost in the libusb conversion was a call to USBDEVFS_DISCONNECT to first detach any such drivers. Reintroduce this by invoking libusb_detach_kernel_driver().
As with some other libusb functions there are multiple return values denoting "success", so rely on libusb_claim_interface() to catch the actual errors.
Reported-by: Maxim Akristiniy
Suggested-by: Maxim Akristiniy
> usb: Attempt detaching kernel driver

- usb.c
The documentation for libusb_bulk_transfer() specifies that in the event that the read or write request is split into multiple chunks, some of these may still be transferred despite a LIBUSB_ERROR_TIMEOUT is returned.
In the transition to libusb this detail was missed and completed read transfers are sometimes considred to be timeouts and the data discarded, obviously resulting in failure to continue.
Consider the "transferred" value in the event of timeout, to avoid this.
Although not yet spotted in testing, the same logic is introduced for the write path.
> usb: Correct libusb timeout handling

- qdl.c
- qdl.h
- usb.c
Since commit 760b3dffb03d ("qdl: Rework qdl_write to limit write sizes to out_maxpktsize") outgoing transfers has been chunked into blocks of wMaxPacketSize.
As reported by Wiktor Drewniak, Maksim Paimushkin, and Luca Weiss in [1] there's huge benefits to be found in reverting this change, but out of caution the limit was untouched.
With the transition to libusb, the throughput dropped another ~15% on my machine. The numbers for HighSpeed and SuperSpeed are also in the same ballpark.
With SuperSpeed, benchmarking of different chunk sizes in the megabyte range shows improvement over these numbers in the range of 15-20x on the same machine/board combination.
The bug report related to the reduction in size describes a host machine running out of swiotlb, from the fact that we requested 1MB …
> usb: Allow overriding bulk write size and increase default

- firehose.c
- program.c
- program.h
- qdl.c
- qdl.h
When parsing XML files the specified binary to be flashed may not be present. The default behaviour of QDL is to ignore missing file. This is sometimes undesireble.
This patch introduces optional flag --fail-on-missing which will enforce failure of flashing procedure if there is a missing file name.
> qdl: firehose: program: fail on missing file

- firehose.c
During the introduction of UFS provisioning, the author left behind an additional safety measure of forcing the user to explicitly modify the source and recompile QDL in order to be able to lock the provisioning, to avoid users accidentally doing so.
While it does reduce the risk of irreversable mistakes, it's not suitable when QDL is distributed as a binary - and the user already need to set bConfigDescrLock both in provided XML files and on command line.
So, let's remove the safety net...
> firehose: Allow bConfigDescrLock to be passed as 1

- .github/workflows/build.yml
v2 has been deprecated for a while now, and generates a bunch of warnings each time an action is executed.
> .github: use actions/checkout v4

- qdl.c
--serial and --out-chunk-size are parameters which were added recently
to qdl, but the print_usage() function was not updated accordingly.
> qdl: fixup usage function

- firehose.c
- ufs.c
- ufs.h
WriteBooster is a new feature added in UFS3.1. There are new paramaters in the UFS header config. Trying to provision a 3.1+ device without these parameters fail.
Also make sure that we don't send them on older devices.
> ufs: add support for UFS WriteBooster feature

- firehose.c
- patch.c
- patch.h
- program.c
- program.h
- qdl.c
- qdl.h
- sahara.c
- usb.c
- util.c
Attempting to debug a bug report with Valgrind highlighted a number of issues in the implementation. The issue turned out to exist elsewhere, but let's resolve all the reported issues, to make Valgrind more useful in detecting future issues - and to improve the quality of the code.
> For linux msm/valgrind fixes

- firehose.c
- program.c
- program.h
Builds with multiple copies of the primary bootloader does not make sense, but after successfully flashing all the partitions of such build it makes more sense to make one of them bootable, at least more than skipping the step and saying that none was found.
Pick the first found primary bootloader and warn the user about the situation.
> firehose: Handle multiple primary bootloaders

- Makefile
- firehose.c
- patch.c
- program.c
- qdl.c
- qdl.h
- read.c
- sahara.c
- ufs.c
- usb.c
- ux.c
Long pending overhaul of the mix of things being generated on stdout/stderr...
> For linux msm/flashing progress

- .gitignore
- Makefile
- ks.c
- qdl.c
- qdl.h
- ramdump.c
- util.c
> RFC: implement version information

- Makefile
Small fixes for two errors:
- call wrong dependency
- allow VERSION to be passed into Makefile
See commit messages for details.
cc @ndechesne @andersson @quic-bjorande
> Some fixes for --version argument.

- Makefile
Using fake target name forces make to rebuild all targets that depend on it. Properly specify version.h as a target name and use double-colon to let make know that it's a special build target.
> make: don't rebuild util.o (and dependencies) unnecessary

- .github/workflows/build.yml
Ubuntu 20.04 has been disabled on GitHub. Stop using it for building images.
> CI: disable Ubuntu 20.04 builds

- .github/workflows/build.yml
- .gitignore
- Makefile
- firehose.c
- ks.c
- oscompat.c
- oscompat.h
- program.c
- qdl.c
- ramdump.c
- read.c
- sahara.c
- usb.c
- ux.c
This adds the ability to build and run qdl on Windows. It's an alternative approach to #94 using MSYS2 MINGW64 instead of Visual Studio in order to have a smaller OS compatibility layer.
The CI job also uploads artifacts to make it easier to validate on different systems.
I wanted to open this for feedback before it's ready to merge.
The main gap right now are the [err functions](https://man7.org/linux/man-pages/man3/err.3.html) that are not available on MINGW64. This is something other projects had to deal with https://github.com/YosysHQ/icestorm/issues/85. Before implementing a solution to this, I wanted to get opinions on these options: replace `err` functions in the project with a portable alternative, or implement compatible versions in `oscompat.c`.
- I ended up implementing …
> Windows build

- sahara.c
Fix build warning in sahara protocol implementation: sahara.c: In function ‘sahara_debug64_one’:
sahara.c:348:25: warning: ignoring return value of ‘write’
declared with attribute ‘warn_unused_result’ [-Wunused-result]
348 |                         write(fd, buf, n);
|                         ^~~~~~~~~~~~~~~~~
> sahara: fix ignoring return value warning

- program.c
- program.h
- qdl.c
Introduce the `--allow-fusing` parameter, which must be explicitly set if the `secdata` partition is programmed, as it will lead to irreversible changes (fuses will be blown during the next boot).
> qdl: introduce allow-fusing parameter 

- firehose.c
- program.c
Erase operations are currently only supported on devices using NAND storage. With this change, erase operations also work on devices with UFS storage.
> Allow erasing all storage types

- usb.c
Tested with Thundercomm TurboX C6490 SoM board.
> usb: add new USB pid 0x901d for Qualcomm QCM6490

- Makefile
- firehose.c
- io.c
- qdl.c
- qdl.h
- ramdump.c
- sahara.c
- sim.c
- usb.c
This mode assists in validating the `rawprogram_.xml` and `patch_.xml` files,  as well as the Firehose commands that are expected to be sent to the Firehose programmer.
Dry run implementation is also expected to be extended for the Digests Table generation required for Firehose Validated Image Programming (VIP).
Example of usage:
```
$ qdl --dry-run --serial=0AA94EFD --debug prog_firehose_ddr.elf rawprogram*.xml patch*.xml qdl version v2.1-24-g30ac3a8-dirty
This is a dry-run execution of QDL. No actual flashing has been performed waiting for programmer...
FIREHOSE WRITE: <?xml version="1.0"?>
<data><configure MemoryName="ufs" MaxPayloadSizeToTargetInBytes="1048576" verbose="0" ZLPAwareHost="1" SkipStorageInit="0"/></data>
FIREHOSE WRITE: <?xml version="1.0"?>
<data><configure …
```
> qdl: add support for dry run execution

- usb.c
```text
usb.c: In function ‘usb_init’:
usb.c:295:34: error: implicit declaration of function ‘malloc’ [-Wimplicit-function-declaration]
295 |         struct qdl_device *qdl = malloc(sizeof(struct qdl_device_usb));
|                                  ^~~~~~
usb.c:11:1: note: include ‘<stdlib.h>’ or provide a declaration of ‘malloc’
10 | #include "qdl.h"
+++ |+#include <stdlib.h>
11 | 
usb.c:295:34: warning: incompatible implicit declaration of built-in function ‘malloc’ [-Wbuiltin-declaration-mismatch]
295 |         struct qdl_device *qdl = malloc(sizeof(struct qdl_device_usb));
|                                  ^~~~~~
usb.c:295:34: note: include ‘<stdlib.h>’ or provide a declaration of ‘malloc’
make: *** [<builtin>: usb.o] Error 1
```
#55 again
`malloc` usage is introduced here …
> Include stdlib in usb.c

- Makefile
- firehose.c
- qdl.c
- qdl.h
- sha2.c
- sha2.h
- sim.h
- usb.c
- vip.c
- vip.h
```
Add support for Digests Table generation for Validated Image
Programming (VIP), which is activated when Secure Boot is enabled
on the target. VIP controls which packets are allowed to be issued to
the target. Controlling the packets that can be sent to the target is
done through hashing. The target applies a hashing function to all
received data, comparing the resulting hash digest against an existing
digest table in memory. If the calculated hash digest matches the next
entry in the table, the packet (data or command) is accepted; otherwise,
the packet is rejected, and the target halts.
This change introduces logic for VIP table generation.
In the current VIP design the first signed hash table can be a
maximum of 8 KB. Considering that it must be in MBN format, and in
addition to the …
```
> VIP table generation

- firehose.c
- io.c
- patch.c
- program.c
- qdl.c
- read.c
- sahara.c
- sha2.c
- sha2.h
- sim.c
- sim.h
- ufs.c
- ufs.h
- util.c
- vip.c
- vip.h
Add SPDX-License-Identifier line to each source file that contains license text. More details about SPDX license identifiers can be found at [1].
The scancode-toolkit [2] was used to match license text to the correct SPDX-License-Identifier:
$ scancode --license --copyright --html scancode_result.html ./
[1] https://spdx.org/licenses/
[2] https://github.com/nexB/scancode-toolkit
> qdl: add SPDX license identifiers

- README.md
On linux, there is no package named libusb available through apt. On running make, I found that the default version of libusb (libusb-1.0-0) does not work. Upon further testing, I found libusb-1.0-0-dev does work. Therefore, update the name of the libusb package to be installed for linux.
> Fix linux command to install libusb

- firehose.c
- program.c
- program.h
- sparse.c
- sparse.h
There are a few different integer overflows in the sparse code, resulting in data corruption when flashing large images etc.
While at it, clean up the endianness in the code.
This is likely the problem reported in #124
> For linux msm/sparse int overflow

- Makefile
- README.md
- firehose.c
- gpt.c
- gpt.h
- program.c
- program.h
- qdl.c
- qdl.h
- read.c
- read.h
- util.c
Introduce support for specifying "read" and "write" commands directly on the command line, with addressing of physical partition, sector, sector+length and/or GPT partition names.
> For linux msm/read write gpt

- sahara.c
Sometimes the device ends up in a funky state, resulting in the initial USB read to fail. Rather then just silently exiting with an error code, actually print a message to inform the user.
> sahara: Print an error when device isn't reachable

- patch.c
When invoking QDL in a way that doesn't involve patching (e.g. by invoking a read) the "0 patches applied" is annoying and can be confusing.
Make this statement conditional on patch files actually having been loaded.
> patch: Don't spam the log when no patch file was loaded

- gpt.c
When using first_lba and last_lba information from the GPT entry to calculate the number of sectors, we need to add 1 to the result.
Imagine if both values were 1.  This means there is 1 sector of data and the first and last LBA values are same.  However, the current calculation is: num_sectors = last_lba - first_lba.
In this case, it would return a value of 0.  (Always 1 less sector than it should).
Tested on the CDT partition of RB3 Gen2:
In the rawprogram3.xml file it has num_partition_sectors="32" (4096 byte sector size).  This should result in a binary size of 131072.
Pre-patch:
$ qdl --storage ufs prog_firehose_ddr.elf read 3/cdt cdt-bad.bin waiting for programmer...
partition 6 has not GPT header
partition 7 has not GPT header
0 patches applied
read "cdt-bad.bin" successfully
$ ls …
> gpt: gpt_load_table_from_partition: fix off-by-one error for num_sectors
